import type { ThemeColors } from '~/composables/useTheme'

export function serializeKittyTheme(theme: ThemeColors, name = 'theme-lab'): string {
  const lines = [
    `# ${name} - Kitty color scheme`,
    `# Generated with theme-lab`,
    ``,
    `foreground ${theme.fg}`,
    `background ${theme.bg}`,
    ``,
    `selection_foreground ${theme.bg}`,
    `selection_background ${theme.warning}`,
    ``,
    `cursor ${theme.fg}`,
    `cursor_text_color ${theme.bg}`,
    ``,
    `# Black`,
    `color0 ${theme.palette[0]}`,
    `color8 ${theme.palette[8]}`,
    ``,
    `# Red`,
    `color1 ${theme.palette[1]}`,
    `color9 ${theme.palette[9]}`,
    ``,
    `# Green`,
    `color2 ${theme.palette[2]}`,
    `color10 ${theme.palette[10]}`,
    ``,
    `# Yellow`,
    `color3 ${theme.palette[3]}`,
    `color11 ${theme.palette[11]}`,
    ``,
    `# Blue`,
    `color4 ${theme.palette[4]}`,
    `color12 ${theme.palette[12]}`,
    ``,
    `# Magenta`,
    `color5 ${theme.palette[5]}`,
    `color13 ${theme.palette[13]}`,
    ``,
    `# Cyan`,
    `color6 ${theme.palette[6]}`,
    `color14 ${theme.palette[14]}`,
    ``,
    `# White`,
    `color7 ${theme.palette[7]}`,
    `color15 ${theme.palette[15]}`,
  ]

  return lines.join('\n') + '\n'
}
