import type { ThemeColors } from '~/composables/useTheme'

export function serializeWeztermTheme(theme: ThemeColors, name = 'theme-lab'): string {
  const lines = [
    `-- ${name} - WezTerm color scheme`,
    `-- Generated with theme-lab`,
    `-- Add this to your wezterm.lua config`,
    ``,
    `local config = {}`,
    ``,
    `config.colors = {`,
    `  foreground = '${theme.fg}',`,
    `  background = '${theme.bg}',`,
    ``,
    `  cursor_bg = '${theme.keyword}',`,
    `  cursor_fg = '${theme.bg}',`,
    `  cursor_border = '${theme.keyword}',`,
    ``,
    `  selection_fg = '${theme.bg}',`,
    `  selection_bg = '${theme.warning}',`,
    ``,
    `  scrollbar_thumb = '${theme.palette[8]}',`,
    `  split = '${theme.palette[8]}',`,
    ``,
    `  ansi = {`,
    `    '${theme.palette[0]}',`,
    `    '${theme.palette[1]}',`,
    `    '${theme.palette[2]}',`,
    `    '${theme.palette[3]}',`,
    `    '${theme.palette[4]}',`,
    `    '${theme.palette[5]}',`,
    `    '${theme.palette[6]}',`,
    `    '${theme.palette[7]}',`,
    `  },`,
    ``,
    `  brights = {`,
    `    '${theme.palette[8]}',`,
    `    '${theme.palette[9]}',`,
    `    '${theme.palette[10]}',`,
    `    '${theme.palette[11]}',`,
    `    '${theme.palette[12]}',`,
    `    '${theme.palette[13]}',`,
    `    '${theme.palette[14]}',`,
    `    '${theme.palette[15]}',`,
    `  },`,
    `}`,
    ``,
    `return config`,
  ]

  return lines.join('\n') + '\n'
}
