import type { ThemeColors } from '~/composables/useTheme'

export function serializeZshTheme(theme: ThemeColors): string {
  const lines = [
    `# ZSH Syntax Highlighting + FZF color scheme`,
    `# Generated with theme-lab`,
    `# Add this to your ~/.zshrc`,
    ``,
    `# ZSH Syntax Highlighting`,
    `# Requires: https://github.com/zsh-users/zsh-syntax-highlighting`,
    `typeset -A ZSH_HIGHLIGHT_STYLES`,
    ``,
    `ZSH_HIGHLIGHT_STYLES[default]='fg=${theme.fg}'`,
    `ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=${theme.error}'`,
    `ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=${theme.keyword}'`,
    `ZSH_HIGHLIGHT_STYLES[alias]='fg=${theme.function}'`,
    `ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=${theme.function}'`,
    `ZSH_HIGHLIGHT_STYLES[builtin]='fg=${theme.builtin}'`,
    `ZSH_HIGHLIGHT_STYLES[function]='fg=${theme.function}'`,
    `ZSH_HIGHLIGHT_STYLES[command]='fg=${theme.base}'`,
    `ZSH_HIGHLIGHT_STYLES[precommand]='fg=${theme.keyword}'`,
    `ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=${theme.operator}'`,
    `ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=${theme.base}'`,
    `ZSH_HIGHLIGHT_STYLES[path]='fg=${theme.string}'`,
    `ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=${theme.operator}'`,
    `ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=${theme.string}'`,
    `ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg=${theme.operator}'`,
    `ZSH_HIGHLIGHT_STYLES[globbing]='fg=${theme.warning}'`,
    `ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=${theme.number}'`,
    `ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=${theme.variable}'`,
    `ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=${theme.variable}'`,
    `ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=${theme.string}'`,
    `ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=${theme.string}'`,
    `ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=${theme.string}'`,
    `ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=${theme.string}'`,
    `ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=${theme.variable}'`,
    `ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=${theme.variable}'`,
    `ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=${theme.variable}'`,
    `ZSH_HIGHLIGHT_STYLES[assign]='fg=${theme.variable}'`,
    `ZSH_HIGHLIGHT_STYLES[redirection]='fg=${theme.operator}'`,
    `ZSH_HIGHLIGHT_STYLES[comment]='fg=${theme.comment}'`,
    `ZSH_HIGHLIGHT_STYLES[arg0]='fg=${theme.base}'`,
    ``,
    `# FZF Colors`,
    `# Requires: https://github.com/junegunn/fzf`,
    `export FZF_DEFAULT_OPTS="\\`,
    `--color=fg:${theme.fg},bg:${theme.bg},hl:${theme.base} \\`,
    `--color=fg+:${theme.fg},bg+:${theme.palette[0]},hl+:${theme.base} \\`,
    `--color=info:${theme.number},prompt:${theme.base},pointer:${theme.base} \\`,
    `--color=marker:${theme.string},spinner:${theme.warning},header:${theme.comment} \\`,
    `--color=border:${theme.palette[0]},label:${theme.fg},query:${theme.fg}"`,
  ]

  return lines.join('\n') + '\n'
}
