import type { ThemePalette, ExportResult } from '../types'

export function exportAlacritty(palette: ThemePalette, themeName: string = 'vulpes'): ExportResult {
  const content = `# ${themeName} - Alacritty Color Scheme
# Generated by vulpes-theme-lab
# Usage: Add to ~/.config/alacritty/alacritty.toml

[colors.primary]
background = "${palette.bg}"
foreground = "${palette.fg}"

[colors.cursor]
text = "${palette.bg}"
cursor = "${palette.cursor}"

[colors.selection]
text = "${palette.fg}"
background = "${palette.selection}"

[colors.normal]
black = "${palette.palette[0]}"
red = "${palette.palette[1]}"
green = "${palette.palette[2]}"
yellow = "${palette.palette[3]}"
blue = "${palette.palette[4]}"
magenta = "${palette.palette[5]}"
cyan = "${palette.palette[6]}"
white = "${palette.palette[7]}"

[colors.bright]
black = "${palette.palette[8]}"
red = "${palette.palette[9]}"
green = "${palette.palette[10]}"
yellow = "${palette.palette[11]}"
blue = "${palette.palette[12]}"
magenta = "${palette.palette[13]}"
cyan = "${palette.palette[14]}"
white = "${palette.palette[15]}"
`

  return {
    filename: `${themeName}-alacritty.toml`,
    content,
    format: 'alacritty' as any,
  }
}
