import type { ThemePalette, ExportResult } from '../types'

/**
 * Generates a Ghostty terminal theme configuration
 * @param palette - Semantic color palette
 * @param themeName - Name of the theme
 * @returns Ghostty config file content
 */
export function exportGhostty(palette: ThemePalette, themeName: string = 'vulpes'): ExportResult {
  const lines = [
    `# ${themeName} - Ghostty Theme`,
    `# Generated by vulpes-theme-lab`,
    '',
    `background = ${palette.bg}`,
    `foreground = ${palette.fg}`,
    `cursor-color = ${palette.cursor}`,
    `selection-background = ${palette.selection}`,
    `selection-foreground = ${palette.bg}`,
    '',
    '# ANSI Colors (0-15)',
  ]

  // Add palette colors
  for (let i = 0; i <= 15; i++) {
    lines.push(`palette = ${i}=${palette.palette[i]}`)
  }

  return {
    filename: `${themeName}.ghostty`,
    content: lines.join('\n') + '\n',
    format: 'ghostty',
  }
}
