import type { ThemePalette, ExportResult } from '../types'

/**
 * Generates a Lazygit config with custom theme colors in YAML format
 * @param palette - Semantic color palette
 * @param themeName - Name of the theme
 * @returns Lazygit config.yml snippet
 */
export function exportLazygit(palette: ThemePalette, themeName: string = 'vulpes'): ExportResult {
  const content = `# ${themeName} - Lazygit Theme
# Generated by vulpes-theme-lab
# Add this to your ~/.config/lazygit/config.yml

gui:
  theme:
    activeBorderColor:
      - '${palette.base}'
      - bold
    inactiveBorderColor:
      - '${palette.comment}'
    searchingActiveBorderColor:
      - '${palette.warning}'
      - bold
    optionsTextColor:
      - '${palette.info}'
    selectedLineBgColor:
      - '${palette.bg_alt}'
    selectedRangeBgColor:
      - '${palette.bg_alt}'
    cherryPickedCommitBgColor:
      - '${palette.info}'
    cherryPickedCommitFgColor:
      - '${palette.bg}'
    unstagedChangesColor:
      - '${palette.error}'
    defaultFgColor:
      - '${palette.fg}'

  commitLength:
    show: true

  showFileTree: true
  showListFooter: true
  showRandomTip: true
  showBranchCommitHash: false
  showBottomLine: true
  showCommandLog: true

  authorColors:
    "*": '${palette.base}'

  branchColors:
    "main": '${palette.success}'
    "master": '${palette.success}'
    "develop": '${palette.info}'
    "feature/*": '${palette.warning}'
    "fix/*": '${palette.error}'
`

  return {
    filename: 'lazygit-config.yml',
    content,
    format: 'lazygit',
  }
}
