import type { ThemePalette, ExportResult } from '../types'

export function exportNeomutt(palette: ThemePalette, themeName: string = 'vulpes'): ExportResult {
  const content = `# ${themeName} - Neomutt Color Theme
# Generated by vulpes-theme-lab
# Usage: source this file in your ~/.config/neomutt/neomuttrc

# Basic colors
color normal ${palette.fg} ${palette.bg}
color error ${palette.error} ${palette.bg}
color tilde ${palette.comment} ${palette.bg}
color message ${palette.success} ${palette.bg}
color markers ${palette.warning} ${palette.bg}
color attachment ${palette.info} ${palette.bg}
color search ${palette.bg} ${palette.base}
color status ${palette.bg} ${palette.base}
color indicator ${palette.bg} ${palette.base}
color tree ${palette.comment} ${palette.bg}

# Index colors
color index ${palette.fg} ${palette.bg} "~A"
color index ${palette.warning} ${palette.bg} "~N"
color index ${palette.base} ${palette.bg} "~F"
color index ${palette.error} ${palette.bg} "~D"
color index ${palette.info} ${palette.bg} "~T"

# Header colors
color hdrdefault ${palette.comment} ${palette.bg}
color header ${palette.keyword} ${palette.bg} "^(From|To|Cc|Bcc)"
color header ${palette.base} ${palette.bg} "^Subject"
color header ${palette.info} ${palette.bg} "^Date"

# Message body
color quoted ${palette.comment} ${palette.bg}
color quoted1 ${palette.string} ${palette.bg}
color quoted2 ${palette.info} ${palette.bg}
color signature ${palette.comment} ${palette.bg}
color body ${palette.string} ${palette.bg} "(https?|ftp)://[^ >]+"
color body ${palette.info} ${palette.bg} "[a-z0-9._%+-]+@[a-z0-9.-]+\\\\.[a-z]{2,}"

# Sidebar
color sidebar_highlight ${palette.bg} ${palette.base}
color sidebar_new ${palette.success} ${palette.bg}
color sidebar_divider ${palette.comment} ${palette.bg}
`

  return {
    filename: `${themeName}-neomutt.muttrc`,
    content,
    format: 'neomutt' as any,
  }
}
