import type { ThemePalette, ExportResult } from '../types'

/**
 * Generates an Obsidian theme CSS file with semantic color mappings
 * @param palette - Semantic color palette
 * @param themeName - Name of the theme
 * @returns Obsidian .css theme file content
 */
export function exportObsidian(palette: ThemePalette, themeName: string = 'vulpes'): ExportResult {
  const lines = [
    `/* ${themeName} - Obsidian Theme */`,
    `/* Generated by vulpes-theme-lab */`,
    `/* Place in .obsidian/themes/ directory */`,
    '',
    ':root {',
    '  /* Base Colors - Background & Foreground */,',
    `  --color-base-00: ${palette.bg};`,
    `  --color-base-10: ${palette.bg_alt};`,
    `  --color-base-20: ${palette.bg_alt};`,
    `  --color-base-25: ${palette.base}20;`,
    `  --color-base-30: ${palette.comment}40;`,
    `  --color-base-35: ${palette.comment}50;`,
    `  --color-base-40: ${palette.comment}60;`,
    `  --color-base-50: ${palette.comment};`,
    `  --color-base-60: ${palette.fg}80;`,
    `  --color-base-70: ${palette.fg}aa;`,
    `  --color-base-100: ${palette.fg};`,
    '',
    '  /* Text Colors */,',
    `  --text-normal: ${palette.fg};`,
    `  --text-muted: ${palette.comment};`,
    `  --text-faint: ${palette.comment}80;`,
    `  --text-link: ${palette.info};`,
    `  --text-error: ${palette.error};`,
    `  --text-success: ${palette.success};`,
    `  --text-warning: ${palette.warning};`,
    `  --text-accent: ${palette.base};`,
    '',
    '  /* Background Colors */,',
    `  --background-primary: ${palette.bg};`,
    `  --background-primary-alt: ${palette.bg};`,
    `  --background-secondary: ${palette.bg_alt};`,
    `  --background-secondary-alt: ${palette.bg_alt};`,
    `  --background-tertiary: ${palette.bg_alt};`,
    `  --background-modifier-border: ${palette.comment}40;`,
    `  --background-modifier-form-field: ${palette.bg_alt};`,
    `  --background-modifier-form-field-focused: ${palette.base}10;`,
    `  --background-modifier-cover: ${palette.bg}99;`,
    `  --background-modifier-accent: ${palette.base}15;`,
    `  --background-hover: ${palette.base}08;`,
    `  --background-match-highlight: ${palette.warning}20;`,
    '',
    '  /* Interactive Elements */,',
    `  --interactive-normal: ${palette.bg_alt};`,
    `  --interactive-hover: ${palette.base}20;`,
    `  --interactive-accent: ${palette.base};`,
    `  --interactive-accent-rgb: ${hexToRgb(palette.base)};`,
    `  --interactive-accent-hover: ${palette.base}dd;`,
    '',
    '  /* Status Colors */,',
    `  --color-red: ${palette.error};`,
    `  --color-orange: ${palette.warning};`,
    `  --color-yellow: ${palette.warning}dd;`,
    `  --color-green: ${palette.success};`,
    `  --color-blue: ${palette.info};`,
    `  --color-purple: ${palette.base};`,
    `  --color-pink: ${palette.error}cc;`,
    `  --color-cyan: ${palette.info}dd;`,
    '',
    '  /* Checkboxes & Selection */,',
    `  --checkbox-marker-color: ${palette.bg};`,
    `  --scrollbar-active-thumb-bg: ${palette.base}aa;`,
    `  --scrollbar-bg: ${palette.bg_alt};`,
    `  --selection-highlight-bg: ${palette.base}20;`,
    '',
    '  /* Syntax Highlighting */,',
    `  --syntax-normal: ${palette.fg};`,
    `  --syntax-string: ${palette.string};`,
    `  --syntax-keyword: ${palette.keyword};`,
    `  --syntax-number: ${palette.number};`,
    `  --syntax-comment: ${palette.comment};`,
    `  --syntax-function: ${palette.function};`,
    `  --syntax-operator: ${palette.operator};`,
    `  --syntax-type: ${palette.type};`,
    `  --syntax-tag: ${palette.tag};`,
    '',
    '  /* Outline & Headings */,',
    `  --heading-color: ${palette.keyword};`,
    '',
    '}',
  ]

  return {
    filename: `${themeName}.css`,
    content: lines.join('\n') + '\n',
    format: 'obsidian',
  }
}

/**
 * Helper to convert hex color to RGB values for CSS custom properties
 * Some Obsidian features need RGB format: var(--color, r g b)
 */
function hexToRgb(hex: string): string {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex)
  if (!result) return '0, 0, 0'
  return `${parseInt(result[1], 16)}, ${parseInt(result[2], 16)}, ${parseInt(result[3], 16)}`
}
