import type { ThemePalette, ExportResult } from '../types'

/**
 * Generates Tailwind CSS configuration with theme colors
 * Exports both CSS custom properties and a tailwind.config.js extend snippet
 *
 * @param palette - Semantic color palette
 * @param themeName - Name of the theme
 * @returns Tailwind config content
 */
export function exportTailwind(
  palette: ThemePalette,
  themeName: string = 'vulpes'
): ExportResult {
  const lines = [
    `/* ${themeName} - Tailwind CSS Theme */`,
    `/* Generated by vulpes-theme-lab */`,
    '',
    '/* ===========================================',
    '   CSS Custom Properties (recommended)',
    '   Add to your global CSS file',
    '   =========================================== */',
    '',
    ':root {',
    '  /* Base colors */',
    `  --color-bg: ${palette.bg};`,
    `  --color-bg-alt: ${palette.bg_alt};`,
    `  --color-fg: ${palette.fg};`,
    `  --color-base: ${palette.base};`,
    '',
    '  /* Status colors */',
    `  --color-error: ${palette.error};`,
    `  --color-warning: ${palette.warning};`,
    `  --color-success: ${palette.success};`,
    `  --color-info: ${palette.info};`,
    `  --color-hint: ${palette.hint};`,
    '',
    '  /* Syntax/accent colors */',
    `  --color-comment: ${palette.comment};`,
    `  --color-keyword: ${palette.keyword};`,
    `  --color-string: ${palette.string};`,
    `  --color-number: ${palette.number};`,
    `  --color-boolean: ${palette.boolean};`,
    `  --color-function: ${palette.function};`,
    `  --color-constant: ${palette.constant};`,
    `  --color-type: ${palette.type};`,
    `  --color-variable: ${palette.variable};`,
    `  --color-operator: ${palette.operator};`,
    '',
    '  /* UI elements */',
    `  --color-selection: ${palette.selection};`,
    `  --color-cursor: ${palette.cursor};`,
    `  --color-cursorline: ${palette.cursorline};`,
    '',
    '  /* ANSI palette */',
  ]

  // Add ANSI colors
  const ansiNames = [
    'black',
    'red',
    'green',
    'yellow',
    'blue',
    'magenta',
    'cyan',
    'white',
    'bright-black',
    'bright-red',
    'bright-green',
    'bright-yellow',
    'bright-blue',
    'bright-magenta',
    'bright-cyan',
    'bright-white',
  ]

  for (let i = 0; i <= 15; i++) {
    lines.push(`  --color-ansi-${ansiNames[i]}: ${palette.palette[i]};`)
  }

  lines.push('}')
  lines.push('')
  lines.push('/* ===========================================')
  lines.push('   Tailwind Config Extend')
  lines.push('   Add to tailwind.config.js')
  lines.push('   =========================================== */')
  lines.push('')
  lines.push('/*')
  lines.push('// tailwind.config.js')
  lines.push('module.exports = {')
  lines.push('  theme: {')
  lines.push('    extend: {')
  lines.push('      colors: {')
  lines.push(`        // ${themeName} theme`)
  lines.push("        'theme': {")
  lines.push("          'bg': 'var(--color-bg)',")
  lines.push("          'bg-alt': 'var(--color-bg-alt)',")
  lines.push("          'fg': 'var(--color-fg)',")
  lines.push("          'base': 'var(--color-base)',")
  lines.push("          'error': 'var(--color-error)',")
  lines.push("          'warning': 'var(--color-warning)',")
  lines.push("          'success': 'var(--color-success)',")
  lines.push("          'info': 'var(--color-info)',")
  lines.push("          'hint': 'var(--color-hint)',")
  lines.push("          'selection': 'var(--color-selection)',")
  lines.push("          'cursor': 'var(--color-cursor)',")
  lines.push('        },')
  lines.push("        // Or use direct hex values:")
  lines.push(`        // 'bg': '${palette.bg}',`)
  lines.push(`        // 'fg': '${palette.fg}',`)
  lines.push(`        // 'primary': '${palette.base}',`)
  lines.push(`        // 'error': '${palette.error}',`)
  lines.push(`        // 'warning': '${palette.warning}',`)
  lines.push(`        // 'success': '${palette.success}',`)
  lines.push(`        // 'info': '${palette.info}',`)
  lines.push('      },')
  lines.push('    },')
  lines.push('  },')
  lines.push('}')
  lines.push('*/')
  lines.push('')
  lines.push('/* ===========================================')
  lines.push('   Usage Examples')
  lines.push('   =========================================== */')
  lines.push('')
  lines.push('/*')
  lines.push('<!-- With CSS variables -->')
  lines.push('<div class="bg-[var(--color-bg)] text-[var(--color-fg)]">')
  lines.push('  <button class="bg-[var(--color-base)] hover:bg-[var(--color-info)]">')
  lines.push('    Click me')
  lines.push('  </button>')
  lines.push('  <span class="text-[var(--color-error)]">Error text</span>')
  lines.push('</div>')
  lines.push('')
  lines.push('<!-- With extended theme -->')
  lines.push('<div class="bg-theme-bg text-theme-fg">')
  lines.push('  <button class="bg-theme-base hover:bg-theme-info">')
  lines.push('    Click me')
  lines.push('  </button>')
  lines.push('  <span class="text-theme-error">Error text</span>')
  lines.push('</div>')
  lines.push('*/')
  lines.push('')

  return {
    filename: `${themeName}.tailwind.css`,
    content: lines.join('\n'),
    format: 'tailwind',
  }
}
