import type { ThemePalette, ExportResult } from '../types'

export function exportWezterm(palette: ThemePalette, themeName: string = 'vulpes'): ExportResult {
  const content = `-- ${themeName} - WezTerm Color Scheme
-- Generated by vulpes-theme-lab
-- Usage: Place in ~/.config/wezterm/colors/ and reference in wezterm.lua

return {
  foreground = "${palette.fg}",
  background = "${palette.bg}",
  cursor_bg = "${palette.cursor}",
  cursor_border = "${palette.cursor}",
  cursor_fg = "${palette.bg}",
  selection_bg = "${palette.selection}",
  selection_fg = "${palette.fg}",

  ansi = {
    "${palette.palette[0]}",
    "${palette.palette[1]}",
    "${palette.palette[2]}",
    "${palette.palette[3]}",
    "${palette.palette[4]}",
    "${palette.palette[5]}",
    "${palette.palette[6]}",
    "${palette.palette[7]}",
  },

  brights = {
    "${palette.palette[8]}",
    "${palette.palette[9]}",
    "${palette.palette[10]}",
    "${palette.palette[11]}",
    "${palette.palette[12]}",
    "${palette.palette[13]}",
    "${palette.palette[14]}",
    "${palette.palette[15]}",
  },

  tab_bar = {
    background = "${palette.bg_alt}",
    active_tab = {
      bg_color = "${palette.base}",
      fg_color = "${palette.bg}",
    },
    inactive_tab = {
      bg_color = "${palette.bg_alt}",
      fg_color = "${palette.comment}",
    },
    inactive_tab_hover = {
      bg_color = "${palette.bg}",
      fg_color = "${palette.fg}",
    },
    new_tab = {
      bg_color = "${palette.bg_alt}",
      fg_color = "${palette.fg}",
    },
  },
}
`

  return {
    filename: `${themeName}.lua`,
    content,
    format: 'wezterm' as any,
  }
}
