import chroma from 'chroma-js'
import type { ThemePalette, ExportResult } from '../types'

/**
 * Convert color to nearest xterm-256 color code
 * ZSH syntax highlighting uses 256-color palette, not hex colors
 */
function to256(color: string): number {
  const [r, g, b] = chroma(color).rgb()

  // Grayscale check
  if (r === g && g === b) {
    if (r < 8) return 16
    if (r > 248) return 231
    return Math.round(((r - 8) / 247) * 24) + 232
  }

  // Convert to 6x6x6 color cube (16-231)
  const r6 = Math.round((r / 255) * 5)
  const g6 = Math.round((g / 255) * 5)
  const b6 = Math.round((b / 255) * 5)

  return 16 + 36 * r6 + 6 * g6 + b6
}

/**
 * Generates ZSH syntax highlighting and FZF color configuration
 * @param palette - Semantic color palette
 * @param themeName - Name of the theme
 * @returns ZSH config snippet
 */
export function exportZsh(palette: ThemePalette, themeName: string = 'vulpes'): ExportResult {
  // Normalize all colors to hex format using chroma-js
  // This ensures consistent format regardless of input (rgb, hsl, etc.)
  const hex = {
    fg: chroma(palette.fg).hex(),
    bg: chroma(palette.bg).hex(),
    bg_alt: chroma(palette.bg_alt).hex(),
    base: chroma(palette.base).hex(),
    error: chroma(palette.error).hex(),
    warning: chroma(palette.warning).hex(),
    success: chroma(palette.success).hex(),
    info: chroma(palette.info).hex(),
    comment: chroma(palette.comment).hex(),
    keyword: chroma(palette.keyword).hex(),
    string: chroma(palette.string).hex(),
    function: chroma(palette.function).hex(),
    variable: chroma(palette.variable).hex(),
    operator: chroma(palette.operator).hex(),
  }

  // For Powerlevel10k segments, we need high contrast between bg/fg
  // Use chroma to calculate contrast and pick appropriate foreground
  const getContrastFg = (bgColor: string) => {
    const bgLum = chroma(bgColor).luminance()
    // WCAG AA requires 4.5:1 contrast ratio for normal text
    // For terminal prompts, we go even higher for readability
    return bgLum > 0.5 ? '#000000' : '#ffffff'
  }

  const p10k = {
    dir_bg: hex.base,
    dir_fg: getContrastFg(hex.base),
    vcs_clean_bg: hex.success,
    vcs_clean_fg: getContrastFg(hex.success),
    vcs_modified_bg: hex.warning,
    vcs_modified_fg: getContrastFg(hex.warning),
    vcs_untracked_bg: hex.info,
    vcs_untracked_fg: getContrastFg(hex.info),
    status_ok_bg: hex.success,
    status_ok_fg: getContrastFg(hex.success),
    status_error_bg: hex.error,
    status_error_fg: getContrastFg(hex.error),
  }

  // Convert to 256-color codes for ZSH syntax highlighting and Powerlevel10k
  const c256 = {
    fg: to256(hex.fg),
    bg: to256(hex.bg),
    bg_alt: to256(hex.bg_alt),
    base: to256(hex.base),
    error: to256(hex.error),
    warning: to256(hex.warning),
    success: to256(hex.success),
    info: to256(hex.info),
    comment: to256(hex.comment),
    keyword: to256(hex.keyword),
    string: to256(hex.string),
    function: to256(hex.function),
    variable: to256(hex.variable),
    operator: to256(hex.operator),
  }

  const content = `# ${themeName} - ZSH Theme
# Generated by vulpes-theme-lab
# Add this to your ~/.zshrc

# ZSH Syntax Highlighting
# Requires: https://github.com/zsh-users/zsh-syntax-highlighting
# Note: Uses 256-color palette (0-255)
typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[default]='fg=${c256.fg}'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=${c256.error},bold'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=${c256.keyword},bold'
ZSH_HIGHLIGHT_STYLES[alias]='fg=${c256.function}'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=${c256.function}'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=${c256.base}'
ZSH_HIGHLIGHT_STYLES[function]='fg=${c256.function}'
ZSH_HIGHLIGHT_STYLES[command]='fg=${c256.base}'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=${c256.keyword}'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=${c256.operator}'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=${c256.base}'
ZSH_HIGHLIGHT_STYLES[path]='fg=${c256.string}'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=${c256.operator}'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=${c256.string}'
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg=${c256.operator}'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=${c256.warning}'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=${c256.info}'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=${c256.variable}'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=${c256.variable}'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=${c256.string}'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=${c256.string}'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=${c256.string}'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=${c256.string}'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=${c256.variable}'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=${c256.variable}'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=${c256.variable}'
ZSH_HIGHLIGHT_STYLES[assign]='fg=${c256.variable}'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=${c256.operator}'
ZSH_HIGHLIGHT_STYLES[comment]='fg=${c256.comment}'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=${c256.base}'

# FZF Colors
# Requires: https://github.com/junegunn/fzf
# Note: Uses hex colors (#RRGGBB format)
export FZF_DEFAULT_OPTS="\\
--color=fg:${hex.fg},bg:${hex.bg},hl:${hex.base} \\
--color=fg+:${hex.fg},bg+:${hex.bg_alt},hl+:${hex.base} \\
--color=info:${hex.info},prompt:${hex.base},pointer:${hex.base} \\
--color=marker:${hex.success},spinner:${hex.warning},header:${hex.comment} \\
--color=border:${hex.bg_alt},label:${hex.fg},query:${hex.fg}"

# Powerlevel10k Colors
# Requires: https://github.com/romkatv/powerlevel10k
# Add these to your ~/.p10k.zsh before the line that says 'source \${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-\${(%):-%n}.zsh'
# Note: Uses 256-color palette (0-255) and POWERLEVEL9K_ prefix
# Foreground colors are automatically calculated for optimal contrast using chroma-js
typeset -g POWERLEVEL9K_DIR_BACKGROUND=${to256(p10k.dir_bg)}
typeset -g POWERLEVEL9K_DIR_FOREGROUND=${to256(p10k.dir_fg)}
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=${to256(p10k.vcs_clean_bg)}
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=${to256(p10k.vcs_clean_fg)}
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=${to256(p10k.vcs_modified_bg)}
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=${to256(p10k.vcs_modified_fg)}
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=${to256(p10k.vcs_untracked_bg)}
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=${to256(p10k.vcs_untracked_fg)}
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=${to256(p10k.status_ok_bg)}
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=${to256(p10k.status_ok_fg)}
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=${to256(p10k.status_error_bg)}
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=${to256(p10k.status_error_fg)}
`

  return {
    filename: `${themeName}.zsh`,
    content,
    format: 'zsh',
  }
}
