import type { ThemePalette, ExportResult } from '../types'

/**
 * Generates ZSH syntax highlighting and FZF color configuration
 * @param palette - Semantic color palette
 * @param themeName - Name of the theme
 * @returns ZSH config snippet
 */
export function exportZsh(palette: ThemePalette, themeName: string = 'vulpes'): ExportResult {
  const content = `# ${themeName} - ZSH Theme
# Generated by vulpes-theme-lab
# Add this to your ~/.zshrc

# ZSH Syntax Highlighting
# Requires: https://github.com/zsh-users/zsh-syntax-highlighting
typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[default]='fg=${palette.fg}'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=${palette.error}'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=${palette.keyword}'
ZSH_HIGHLIGHT_STYLES[alias]='fg=${palette.function}'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=${palette.function}'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=${palette.base}'
ZSH_HIGHLIGHT_STYLES[function]='fg=${palette.function}'
ZSH_HIGHLIGHT_STYLES[command]='fg=${palette.base}'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=${palette.keyword}'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=${palette.operator}'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=${palette.base}'
ZSH_HIGHLIGHT_STYLES[path]='fg=${palette.string}'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=${palette.operator}'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=${palette.string}'
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg=${palette.operator}'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=${palette.warning}'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=${palette.info}'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=${palette.variable}'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=${palette.variable}'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=${palette.string}'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=${palette.string}'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=${palette.string}'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=${palette.string}'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=${palette.variable}'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=${palette.variable}'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=${palette.variable}'
ZSH_HIGHLIGHT_STYLES[assign]='fg=${palette.variable}'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=${palette.operator}'
ZSH_HIGHLIGHT_STYLES[comment]='fg=${palette.comment}'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=${palette.base}'

# FZF Colors
# Requires: https://github.com/junegunn/fzf
export FZF_DEFAULT_OPTS="\\
--color=fg:${palette.fg},bg:${palette.bg},hl:${palette.base} \\
--color=fg+:${palette.fg},bg+:${palette.bg_alt},hl+:${palette.base} \\
--color=info:${palette.info},prompt:${palette.base},pointer:${palette.base} \\
--color=marker:${palette.success},spinner:${palette.warning},header:${palette.comment} \\
--color=border:${palette.bg_alt},label:${palette.fg},query:${palette.fg}"

# FZF Preview colors (for bat integration)
export FZF_PREVIEW_OPTS="--color=always --theme=${themeName}"
`

  return {
    filename: `${themeName}.zsh`,
    content,
    format: 'zsh',
  }
}
